theme: jekyll-theme-minimal

title: [Raúl Aguirre-Gamboa]
description: [Personal website]

[google scholar page](https://scholar.google.com.mx/citations?user=s54WJmAAAAAJ&hl=en)

#logo: [Location of the logo]
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]