---
title: "About Me"
---

Born and partially raised in [Monterrey](https://en.wikipedia.org/wiki/Monterrey), México. I studied Bachelor in Genomic Biotechnology (a newly created bachelor at that time ~2005), where I became hooked with research and specially with computational biology where we can leaverage computational and statistical techniques to answer complex biological questions. After concluding my BSc, I started a Masters degree in Bioinformatics at the [Tecnológico de Monterrey](https://tec.mx/en), where I became an intern at the Bioinformatics lab at the National School of Medical Sciences under the supervission of [Prof. Victor Treviño](http://www.tecgradschool.mx/teachers/phd/computer-science/victor-manuel-trevino-alvarado-phd). At Dr. Treviño's lab we developed and implemented two web tools: [SurvExpress](http://bioinformatica.mty.itesm.mx:8080/Biomatec/SurvivaX.jsp) (Aguirre-Gamboa et al. 2013) and [SurvMicro](http://bioinformatica.mty.itesm.mx:8080/Biomatec/Survmicro.jsp) (Aguirre-Gamboa and Trevino 2014). SurvExpress and SurvMIcro are built on databases of ≥39,000 transcriptionally profiled and ≥4,000 microRNA cancer biopsies that have been associated to an outcome-like phenotype  such as time-to-survival or time-to-response. We used this database to provide users with an easy-to-use platform that evaluates, in multivariate fashion, if their gene sets/biomarkers are significantly associated to time-to-outcome phenotypes in multiple types of cancer.

In 2014, I started my PhD at the [University Medical Center Groningen](https://www.umcg.nl) in the Netherlands where I joined the research group of [Prof. Cisca Wijmenga](https://www.rug.nl/research/genetics/staff/cisca-wijmenga) under the co-supervision of [Dr. Yang Li](https://www.rug.nl/research/genetics/staff/yang-li?lang=en). I became involved in the data analysis team of the 500FG cohort, a study within the Human Functional Genomics Project [(HFGP)](http://www.humanfunctionalgenomics.org/) (Netea et al. 2016). The [500FG cohort](http://www.humanfunctionalgenomics.org/site/?page_id=82) consists of 500 Dutch individuals who were deeply immuno-phenotyped. The data collected included cell counts of adaptive immune subpopulations through FACS (Aguirre-Gamboa et al. 2016) and cytokine production upon ex vivo simulations (Li et al. 2016). Within the HFGP, I was responsible for the analysis performed on the cell counts (Aguirre-Gamboa et al. 2016), where we described the genetic component behind cell composition through QTL mapping and quantified the percentage of variance explained by common genetic variations. We discovered that nearly all B cell subtypes quantified in this study were significantly associated with seasonal effects, indicating that their levels were significantly different between summer and winter. Furthermore, we performed an integrative analysis using all available layers of molecular information gathered in the 500FG cohort to describe how much of the inter-individual variation in immune response (up to 67% for certain responses) upon stimulation by  multiple pathogens can be explained by integrating baseline immune and molecular parameters and genetic information (Bakker et al. 2018). 

## References

Aguirre-Gamboa, Raul, Hugo Gomez-Rueda, Emmanuel Martínez-Ledesma, Antonio Martínez-Torteya, Rafael Chacolla-Huaringa, Alberto Rodriguez-Barrientos, José G. Tamez-Peña, and Victor Treviño. 2013. “SurvExpress: An Online Biomarker Validation Tool and Database for Cancer Gene Expression Data Using Survival Analysis.” PloS One 8 (9): e74250.

Aguirre-Gamboa, Raul, Irma Joosten, Paulo C. M. Urbano, Renate G. van der Molen, Esther van Rijssen, Bram van Cranenbroek, Marije Oosting, et al. 2016. “Differential Effects of Environmental and Genetic Factors on T and B Cell Immune Traits.” Cell Reports 17 (9): 2474–87.

Aguirre-Gamboa, Raul, and Victor Trevino. 2014. “SurvMicro: Assessment of miRNA-Based Prognostic Signatures for Cancer Clinical Outcomes by Multivariate Survival Analysis.” Bioinformatics  30 (11): 1630–32.
Bakker, Olivier B., Raul Aguirre-Gamboa, Serena Sanna, Marije Oosting, Sanne P. Smeekens, Martin Jaeger, Maria Zorro, et al. 2018. “Integration of Multi-Omics Data and Deep Phenotyping Enables Prediction of Cytokine Responses.” Nature Immunology 19 (7): 776–86.

Li, Yang, Marije Oosting, Sanne P. Smeekens, Martin Jaeger, Raul Aguirre-Gamboa, Kieu T. T. Le, Patrick Deelen, et al. 2016. “A Functional Genomics Approach to Understand Variation in Cytokine Production in Humans.” Cell 167 (4): 1099–1110.e14.

Netea, Mihai G., Leo A. B. Joosten, Yang Li, Vinod Kumar, Marije Oosting, Sanne Smeekens, Martin Jaeger, et al. 2016. “Understanding Human Immune Function Using the Resources from the Human Functional Genomics Project.” Nature Medicine 22 (8): 831–33.