---
title: "My personal website"
---

My name is Raúl Aguirre-Gamboa, at the moment I'm wrapping up my PhD thesis while working as a research associate at the [Department of Genetics](https://www.rug.nl/research/genetics/?lang=en) at the [University Medical Center of Groningen](https://www.umcg.nl/NL/Zorg/paginas/Default.aspx). My main research interest is to understand the inter-individual variation of the human immune response in health and disease. I investigate this by applying computational and statistical methods to deeply-phenotyped cohorts where millions of data points have been measured. I enjoy working on dynamic and collaborative projects were researchers from diverse backgrounds work together to try to comprehend complex biological phenomena.

Please visit my [Google Scholar](https://scholar.google.com.mx/citations?user=s54WJmAAAAAJ&hl=en) page for a complete list of my publications. 
For more information about my current and previews work you can also take a look at my [CV](https://docs.google.com/document/d/1V0HKDA_fd4g1UATKfAMQf20Z1EXmmmUIkEkpZZLja0o/preview)
